# Site settings
title: Javier Pérez
description: >-
  Personal coding projects portfolio. Check my <a href="https://github.com/p3javier" target="_blank" rel="noopener">@github</a>.
lang: en-US
timezone: Europe/Madrid
image: assets/img/ogp.png # This image used for Open Graph more info https://ogp.me/
repo: https://github.com/p3javier/portfolio-jekyll-static-site
mode: dark # default theme "dark" | "light"

# Profile settings
author:
  name: Javier Pérez
  bio: >-
    <p>Hi, I'm Javier a programmer specialized on Chrome extensions development. I'm also code for the web, my usual stack is: React + Redux + Express + Node.js + MySQL (or MariaDB) and additionally Python for specific things where it is more handy than JS.</p>
    <p>Additionally I work as a Google Ads technician providing support to Google Ads, Analytics, Merchant Center & Tag Manager customers.</p>
    <p>Find me on:</p>
    <ul>
    <li><a href="https://github.com/p3javier/" target="_blank" rel="noopener">@github</a>.</li>
    <li><a href="https://www.linkedin.com/in/javier-perez-aragon/" target="_blank" rel="noopener">@linkedin</a>.</li>
  username: username
  email: your-email@email.com
  avatar: /assets/img/avatar.jpg

# Url settings
url: "https://pejavier.com" #configurar mas adelante
baseurl:
permalink: /:title/
google_analytics:
fb_appid:

# Collection setting
collections:
  posts:
    output: true

# Markdown settings
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge

# Default front matter
defaults:
  - scope:
      path: ""
    values:
      layout: post
      comments: false

# Jekyll Compose default front matter
jekyll_compose:
  post_default_front_matter:
    modified:
    tags: []
    description:
  draft_default_front_matter:
    modified:
    tags: []
    description:

# Build settings
sass:
  style: compressed

include:
  - _redirects
  - .htaccess

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - CHANGELOG.md
  - README.md
  - node_modules
  - CODE_OF_CONDUCT.md

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sass-converter
  - jekyll-sitemap
  - jekyll-postfiles
